# ワールド名を設定するところです。
# 逃走中で使用するワールド名を指定しないと、プラグインが正常に動作しません。
worldName: "world"

# コマンドを使用できるプレイヤーです。
# UUIDで指定してください。また、大文字小文字を区別します。
permissionHaves:
  - e2b3476a-8e03-4ee9-a9c4-e0bf61641c55

# 配信者リストです。
# ここに記載されてるプレイヤーは一部コマンドを除いて運営と同じ機能が使用できます。
# UUIDで指定してください。また、大文字小文字を区別します。
broadCasters: []

# 設定ファイルのバージョンです。変更しないでください。
version: 1.3