name: A_TosoGame_Live
version: @version@
api-version: 1.13
main: jp.aoichaan0513.A_TosoGame_Live.Main
authors: [Aoichaan0513]
website: https://aoichaan0513.jp
description: TosoGame (Run for Money) Plugin for Minecraft Java Edition 1.15.2. (Build @projectBuildDate@)

commands:
  toso:

  start:
  end:
    aliases:
      - g_end
  reset:
  mission:
  hunter:
  tuho:
  player:

  broadcaster:
    aliases:
      - yt
      - lhide
      - lshow

  h:
  t:

  code:

  opgame:
  shuffle:

  location:
    aliases:
      - loc
  map:

  btp:
  phone:

  join:
  leave:
  disappear:
    aliases:
      - vanish
  appear:
    aliases:
      - unvanish
  hide:
  show:
  spec:
  sidebar:

  script:

  nick:
  ride:
