name: A_TosoGame_Live
version: @version@
api-version: 1.13
main: jp.aoichaan0513.A_TosoGame_Live.Main
authors: [Aoichaan0513]
website: https://aoichaan0513.jp
description: TosoGame (Run for Money) Plugin for Minecraft Java Edition 1.15.2. (Build @projectBuildDate@)

commands:
  toso:
    description: TosoGame Plugin Management Command.

  game:
    description: Game Management Command.
    aliases:
      - start
      - end
      - g_end
      - reset
  mission:
    description: Mission Management Command.
  team:
    description: Team Management Command.

  broadcaster:
    description: Broadcaster Management Command.
    aliases:
      - yt
      - lhide
      - lshow

  h:
  t:

  code:

  opgame:
  shuffle:

  location:
    description: Location Settings Command.
    aliases:
      - loc
  map:
    description: Map Settings Command.

  btp:
  resource:
    description: Load Resource Pack Command.
    aliases:
      - texture
  menu:

  join:
    description: Game Join Command.
  leave:
    description: Game Leave Command.
  disappear:
    description: Player Full Invisible Mode Command.
    aliases:
      - vanish
  appear:
    description: Player Full UnInvisible Mode Command.
    aliases:
      - unvanish
  gamemode:
    description: Change GameMode Command.
    aliases:
      - gm
      - gms
      - gm0
      - gmc
      - gm1
      - gma
      - gm2
      - gmsp
      - gm3
  hide:
    description: Hide Other Players Command.
  show:
    description: Show Other Players Command.
  spec:
    description: Toggle Spectator Mode Command.
  sidebar:

  script:

  nick:
  ride:
